### ISSUE TITLE
add `fuse_config` to `init(...)`

### ISSUE THREAD

**Issue by overheadhunter** [cryptomator/jfuse#13]
Add a second parameter `@Nullable FuseConfig fuseConfig` to `init`:

https://github.com/cryptomator/jfuse/blob/99c0bbc45354fd6da73d5f92b5b534dac02553ca/jfuse-api/src/main/java/org/cryptomator/jfuse/api/FuseOperations.java#L523-L525

Document in the JavaDoc that this is not set when using the libfuse2 API.

**Comment by infeo** [comment]
Closed with merging #18 in 8b3351a0c4e1448e5b0321f1a638a2e441b86f71
