### ISSUE TITLE
Read many files at the same time

### ISSUE THREAD

**Issue by viqbgrg** [cryptomator/jfuse#23]
If you read a lot of files at the same time, it will be very slow when the thread is blocked. Is there any solution?

**Comment by overheadhunter** [comment]
did you mount with `-s` flag?

**Comment by viqbgrg** [comment]
yes, added

**Comment by viqbgrg** [comment]
It doesn't seem to be multi-threaded on arm64

**Comment by overheadhunter** [comment]
> yes, added

then remove it. 😅

**Comment by viqbgrg** [comment]
thanks, it worked
