### ISSUE TITLE
Unneeded read method call

### ISSUE THREAD

**Issue by mohamadkaramidarabi** [cryptomator/jfuse#71]
I’m using the jfuse Java library to create a Windows application similar to OneDrive that manages user files. My files are on the cloud, and I’ve overridden the read function in this library to stream files. However, I have an issue: when I open a directory, the library starts to read files without the user opening them. This causes a ‘not responding’ issue and consumes unneeded internet data. Do anyone have any ideas on how to resolve such an issue? @overheadhunter

**Comment by overheadhunter** [comment]
WinFSP allows mounting a volume as a remote drive, causing the OS to be a bit more restrained regarding I/O.
Maybe this solves your problem?

**Comment by mohamadkaramidarabi** [comment]
The issue is related to Windows Defender scanning. When I turned it off, the unnecessary reads did not appear, but this is not the correct solution. It seems the issue was resolved by the `orun_as_service` flag. @overheadhunter @infeo

**Comment by mohamadkaramidarabi** [comment]
> WinFSP allows mounting a volume as a remote drive, causing the OS to be a bit more restrained regarding I/O. Maybe this solves your problem?

How can I mount as a remote drive?

**Comment by overheadhunter** [comment]
> > WinFSP allows mounting a volume as a remote drive, causing the OS to be a bit more restrained regarding I/O. Maybe this solves your problem?
> 
> How can I mount as a remote drive? @overheadhunter

See this question: ["How to mount as network drive in FUSE API"](https://groups.google.com/g/winfsp/c/857T3o4IEA0/m/GmyL4iqDAwAJ)
