### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by mohamadkaramidarabi** [cryptomator/jfuse#79]
I have **two** issues with FUSE:

1. When I want to delete a folder, FUSE's `rmdir `and `unlink `functions are called for all of the folder's children and their children recursively. I want `rmdir `to only target the parent directory.
2. When I edit a file, for example, an Excel file, it triggers the `unlink `function and then creates a new file. I do not want the `unlink `function to be triggered.

Is there any solution to fix these behaviors?

**Comment by infeo** [comment]
You are asking in the wrong repository. The jfuse project is just a wrapper for the FUSE API, not a filesystem implementation. It might contain examples on how to do that, but these examples are, well, just examples. Of course we welcome improvements of those (:

Nor does it determine how filesystem requests are handled. If you have questions regarding the FUSE protocol itself, check out https://github.com/libfuse/libfuse. If you are using Windows, you also have to consider the translation between the native Windows API and FUSE done by WinFSP (https://github.com/winfsp/winfsp).
